name: tictactoe
description: "A game of tic-tac-toe infinite"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # pub.dev/packages/cupertino_icons
  go_router: ^14.1.4      # pub.dev/packages/go_router
  flutter_svg: ^2.0.10+1  # pub.dev/packages/flutter_svg
  lottie: ^3.1.2          # pub.dev/packages/lottie
  flutter_localizations:  # pub.dev/packages/flutter_localizations
    sdk: flutter
  intl: ^0.19.0           # pub.dev/packages/intl
  intl_utils: ^2.8.7      # pub.dev/packages/intl_utils
  audioplayers: ^6.0.0
  provider: ^6.1.2
  showcaseview: ^3.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0           # https://pub.dev/packages/flutter_lints
  build_runner: ^2.4.10           # https://pub.dev/packages/build_runner
  flutter_gen: ^5.4.0             # https://pub.dev/packages/flutter_gen
  flutter_launcher_icons: ^0.13.1 # https://pub.dev/packages/flutter_launcher_icons

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

flutter:
  generate: true          # Generate the FlutterGen files
  uses-material-design: true  
  
  assets:
    - assets/images/
    - assets/sounds/
    - assets/fonts/
    - assets/animations/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        
flutter_intl:             # Configuration for flutter_intl
  enabled: true
  template-arb-file: intl_pt.arb
  untranslated-messages-file: lib/l10n/untranslated_messages_file.txt
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n/generated
  output-localization-file: app_localizations.dart
  nullable-getter: false




